[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# API Functions configuration
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/ws/*"
  to = "/.netlify/functions/socket"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Function timeout
[functions."*"]
  timeout = 30

[[redirects]]
  from = "/api/notifications/*"
  to = "/.netlify/functions/api/notifications/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify", Cache-Control = "no-cache" }

[[redirects]]
  from = "/api/marketplace-offers"
  to = "/.netlify/functions/api/marketplace-offers"
  status = 200
  force = true
  headers = { X-From = "Netlify", Cache-Control = "no-cache" }

[[redirects]]
  from = "/api/cargo/*"
  to = "/.netlify/functions/api/cargo/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify", Cache-Control = "no-cache" }

[[redirects]]
  from = "/api/cargo"
  to = "/.netlify/functions/api/cargo"
  status = 200
  force = true
  headers = { X-From = "Netlify", Cache-Control = "no-cache" }